
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Admin_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Menu
     */
    public Admin_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        sellers = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        products = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        incomes = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(136, 137, 185));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(64, 64, 64));
        panel1.setLayout(new java.awt.BorderLayout());

        admin.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        admin.setForeground(new java.awt.Color(230, 237, 183));
        admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin.setText("Manage Admins");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMouseExited(evt);
            }
        });
        panel1.add(admin, java.awt.BorderLayout.CENTER);

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 290, 50));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close_window_30px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, 30));

        panel2.setBackground(new java.awt.Color(64, 64, 64));
        panel2.setLayout(new java.awt.BorderLayout());

        sellers.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        sellers.setForeground(new java.awt.Color(230, 237, 183));
        sellers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sellers.setText("Manage Sellers");
        sellers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sellersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sellersMouseExited(evt);
            }
        });
        panel2.add(sellers, java.awt.BorderLayout.CENTER);

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 290, 50));

        panel3.setBackground(new java.awt.Color(64, 64, 64));
        panel3.setLayout(new java.awt.BorderLayout());

        products.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        products.setForeground(new java.awt.Color(230, 237, 183));
        products.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        products.setText("Manage Products");
        products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productsMouseExited(evt);
            }
        });
        panel3.add(products, java.awt.BorderLayout.CENTER);

        jPanel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 290, 50));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 237, 183));
        jLabel2.setText("Select your category");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        panel4.setBackground(new java.awt.Color(64, 64, 64));
        panel4.setLayout(new java.awt.BorderLayout());

        incomes.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        incomes.setForeground(new java.awt.Color(230, 237, 183));
        incomes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomes.setText("Check Incomes");
        incomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                incomesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                incomesMouseExited(evt);
            }
        });
        panel4.add(incomes, java.awt.BorderLayout.CENTER);

        jPanel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, 50));

        clear_btn.setBackground(new java.awt.Color(136, 137, 185));
        clear_btn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(230, 237, 183));
        clear_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back_to_40px.png"))); // NOI18N
        clear_btn.setBorder(null);
        clear_btn.setFocusable(false);
        clear_btn.setOpaque(false);
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        jPanel1.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        System.exit(0);

    }//GEN-LAST:event_closeMouseClicked

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed

        setVisible(false);
        LogIn obj = new LogIn( );
        obj.setVisible(true);
        
    }//GEN-LAST:event_clear_btnActionPerformed

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered

        panel1.setBackground(new Color(128, 128, 128));
        
    }//GEN-LAST:event_adminMouseEntered

    private void adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseExited
        
        panel1.setBackground(new Color(64,64,64));
        
    }//GEN-LAST:event_adminMouseExited

    private void sellersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellersMouseEntered
        panel2.setBackground(new Color(128, 128, 128));
    }//GEN-LAST:event_sellersMouseEntered

    private void sellersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellersMouseExited
        panel2.setBackground(new Color(64,64,64));
    }//GEN-LAST:event_sellersMouseExited

    private void productsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseEntered
        panel3.setBackground(new Color(128, 128, 128));

    }//GEN-LAST:event_productsMouseEntered

    private void productsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseExited
        panel3.setBackground(new Color(64,64,64));

    }//GEN-LAST:event_productsMouseExited

    private void incomesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incomesMouseEntered
        panel4.setBackground(new Color(128, 128, 128));

    }//GEN-LAST:event_incomesMouseEntered

    private void incomesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incomesMouseExited
        panel4.setBackground(new Color(64,64,64));

    }//GEN-LAST:event_incomesMouseExited

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked

        setVisible(false);
        Admin_Management obj = new Admin_Management();
        obj.setVisible(true);
        
    }//GEN-LAST:event_adminMouseClicked

    private void sellersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellersMouseClicked

        setVisible(false);
        Seller_Management obj = new Seller_Management();
        obj.setVisible(true);
        
    }//GEN-LAST:event_sellersMouseClicked

    private void productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseClicked

        setVisible(true);
        Product_Management obj = new Product_Management();
        obj.setVisible(true);
        
    }//GEN-LAST:event_productsMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel close;
    private javax.swing.JLabel incomes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JLabel products;
    private javax.swing.JLabel sellers;
    // End of variables declaration//GEN-END:variables
}
