
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */

import javax.swing.*;
import java.awt.*;
import java.sql.*;

public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        choice_cb = new javax.swing.JComboBox<>();
        forgot = new javax.swing.JLabel();
        password_txt = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(136, 137, 185));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user_male_125px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close_window_30px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 237, 183));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 90, 40));

        id_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        id_txt.setForeground(new java.awt.Color(230, 237, 183));
        id_txt.setOpaque(false);
        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });
        jPanel1.add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 160, 40));

        choice_cb.setBackground(new java.awt.Color(136, 137, 185));
        choice_cb.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        choice_cb.setForeground(new java.awt.Color(230, 237, 183));
        choice_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Seller" }));
        choice_cb.setFocusable(false);
        choice_cb.setOpaque(false);
        jPanel1.add(choice_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, 40));

        forgot.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        forgot.setForeground(new java.awt.Color(230, 237, 183));
        forgot.setText("Forgot your password?");
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotMouseExited(evt);
            }
        });
        jPanel1.add(forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 150, 20));

        password_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        password_txt.setForeground(new java.awt.Color(230, 237, 183));
        password_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password_txt.setOpaque(false);
        jPanel1.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 160, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 237, 183));
        jLabel4.setText("User-ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 90, 40));

        clear_btn.setBackground(new java.awt.Color(136, 137, 185));
        clear_btn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(230, 237, 183));
        clear_btn.setText("Clear");
        clear_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        clear_btn.setFocusable(false);
        clear_btn.setOpaque(false);
        jPanel1.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 100, 40));

        submit_btn.setBackground(new java.awt.Color(136, 137, 185));
        submit_btn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(230, 237, 183));
        submit_btn.setText("Submit");
        submit_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        submit_btn.setFocusable(false);
        submit_btn.setOpaque(false);
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 100, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(230, 237, 183));
        jLabel5.setText("Category");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        System.exit(0);
        
    }//GEN-LAST:event_closeMouseClicked

    private void forgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseEntered

        forgot.setForeground(Color.BLUE);
        
    }//GEN-LAST:event_forgotMouseEntered

    private void forgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseExited

        forgot.setForeground(new Color(230, 237, 183));
        
    }//GEN-LAST:event_forgotMouseExited


    
    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed

        String username = id_txt.getText();
        String password = new String(password_txt.getPassword());
        String choice = ""+choice_cb.getSelectedItem();
        
        System.out.println(choice);

        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        } catch (java.lang.ClassNotFoundException e) {  System.out.println(e);       }
        


        try {

            Connection c = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BookStore\\src\\database\\BookStore.mdb");
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

       if (choice.equals("Admin")) { 

            ResultSet r = s.executeQuery("SELECT * FROM AdminTable");
        //    System.out.println("Database is connect");
       
            
            r.last();
            r.beforeFirst();
            
            while(r.next()) { 
            
                String user_id = r.getString(2);
                String user_password = r.getString(3);
                
            if (user_id.equals(username)) {
                
                if (user_password.equals(password)) {
                System.out.println("\nUsername and Password are Match");
                setVisible(false);
                Admin_Menu obj = new Admin_Menu( );
                obj.setVisible(true);
                }
            
                else { System.out.println("\nUserID or Password is wrong"); }
            
                //System.out.println(""+user_id+"\t"+user_password);
                
                            }
            
/*            else {  //System.out.println(""+user_id+"\t"+user_password);
                JOptionPane.showMessageDialog(null,"User-ID does not exist.","Please Try Again!",JOptionPane.ERROR_MESSAGE); }*/
            
            }
            
            r.close();
                           } // admin

       if (choice.equals("Seller")) { 

            ResultSet r = s.executeQuery("SELECT * FROM SellerTable");
        //    System.out.println("Database is connect");
       
            
            r.last();
            r.beforeFirst();
            
            while(r.next()) { 
            
                String user_id = r.getString(2);
                String user_password = r.getString(3);
                
            if (user_id.equals(username)) {
                
                if (user_password.equals(password)) {
//                System.out.println("\nUsername and Password are Match");
                setVisible(false);
                Sales obj = new Sales();
                obj.setVisible(true);
                }
            
                else { System.out.println("\nUserID or Password is wrong"); }
            
                //System.out.println(""+user_id+"\t"+user_password);
                
                            }
            
/*            else {  //System.out.println(""+user_id+"\t"+user_password);
                JOptionPane.showMessageDialog(null,"User-ID does not exist.","Please Try Again!",JOptionPane.ERROR_MESSAGE); }*/
            
            }
            
            r.close();
                           } // seller

            s.close();
            c.close();
            
        }catch(SQLException se){ }
            
        
    }//GEN-LAST:event_submit_btnActionPerformed

    private void forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseClicked


        ForgotPassword obj = new ForgotPassword();
        obj.setVisible(true);
        
    }//GEN-LAST:event_forgotMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choice_cb;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel close;
    private javax.swing.JLabel forgot;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
