import javax.swing.*;
import java.awt.*;
import java.sql.*;

public class RecoverPassword extends javax.swing.JFrame {

String user_id = ForgotPassword.user_id;
String type = ""+user_id.charAt(0);

    public RecoverPassword() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        new_txt = new javax.swing.JTextField();
        confirm_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        clear_btn2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(136, 137, 185));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        title.setForeground(new java.awt.Color(230, 237, 183));
        title.setText("Welcome from Password Recovery, "+ForgotPassword.user_id);
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 270, 20));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 237, 183));
        jLabel6.setText("Please recover your password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        new_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        new_txt.setForeground(new java.awt.Color(230, 237, 183));
        new_txt.setOpaque(false);
        new_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_txtMouseClicked(evt);
            }
        });
        new_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_txtActionPerformed(evt);
            }
        });
        jPanel1.add(new_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 380, 40));

        confirm_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        confirm_txt.setForeground(new java.awt.Color(230, 237, 183));
        confirm_txt.setOpaque(false);
        confirm_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirm_txtMouseClicked(evt);
            }
        });
        confirm_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_txtActionPerformed(evt);
            }
        });
        jPanel1.add(confirm_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 380, 40));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 237, 183));
        jLabel7.setText("Confirm Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        clear_btn2.setBackground(new java.awt.Color(136, 137, 185));
        clear_btn2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        clear_btn2.setForeground(new java.awt.Color(230, 237, 183));
        clear_btn2.setText("Confirm");
        clear_btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        clear_btn2.setFocusable(false);
        clear_btn2.setOpaque(false);
        clear_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(clear_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 80, 40));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 237, 183));
        jLabel8.setText("New Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jPanel2.setBackground(new java.awt.Color(62, 54, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close_window_30px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        setVisible(false);
    }//GEN-LAST:event_closeMouseClicked

    private void new_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_new_txtMouseClicked

    private void new_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_txtActionPerformed

    private void confirm_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirm_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_txtMouseClicked

    private void confirm_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_txtActionPerformed

    private void clear_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btn2ActionPerformed

        String newpas = new_txt.getText();
        String conpas = confirm_txt.getText();
        
        if (newpas.equals(conpas)) {
            
                    try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        } catch (java.lang.ClassNotFoundException e) {  System.out.println(e);       }
        
        
        try {

            Connection c = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BookStore\\src\\database\\BookStore.mdb");
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

            if (type.equals("A")) {
                
            ResultSet r = s.executeQuery("SELECT * FROM AdminTable");
            
            r.last();
            r.beforeFirst();
            while(r.next()) {
                
                String db_id = r.getString(2);
                
                if (db_id.equals(user_id)) {
                    
                    r.updateString(3,conpas);
                    r.updateRow();
                    JOptionPane.showMessageDialog(null,"Your password has changed.","Success",JOptionPane.PLAIN_MESSAGE);
                }
                
                
            }
            
            r.close();
            }

            if (type.equals("S")) {
                
            ResultSet r = s.executeQuery("SELECT * FROM SellerTable");
            
            r.last();
            r.beforeFirst();
            while(r.next()) {
                
                String db_id = r.getString(2);
                
                if (db_id.equals(user_id)) {
                    
                    r.updateString(3,conpas);
                    r.updateRow();
                    JOptionPane.showMessageDialog(null,"Your password has changed.","Success",JOptionPane.PLAIN_MESSAGE);
                    
                }
                
            }
            
            r.close();
            }
            
            s.close();
            c.close();
        }catch(SQLException se) { }
            
        }
        
    }//GEN-LAST:event_clear_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoverPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoverPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoverPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoverPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_btn2;
    private javax.swing.JLabel close;
    private javax.swing.JTextField confirm_txt;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField new_txt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
