import javax.swing.*;
import java.awt.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;


public class Sales extends javax.swing.JFrame {

public String bookname="";
public String bookid="";
public String bookauthor="";
public String bookprice="";
public int allcost=0;
public int y=0;

public static int total=0;

public static String db_bookquantity="";

        String title = "========================== Book Store========================\n" +
"\n" +
"ID	Name		Price	Quantity\n" +
"--------------------------------------------------------------------------------------------------------";

    
    public Sales() {
        initComponents();    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        clear_btn = new javax.swing.JButton();
        show_btn = new javax.swing.JButton();
        search_btn = new javax.swing.JLabel();
        search_name_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        name_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        price_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        qty_txt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        total_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buy_btn = new javax.swing.JButton();
        addcart = new javax.swing.JButton();
        search_btn1 = new javax.swing.JLabel();
        search_name_txt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        payment_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        change_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        print_btn = new javax.swing.JButton();
        clear_btn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(136, 137, 185));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close_window_30px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 30, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 10));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 237, 183));
        jLabel1.setText("Selling Point");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, -1));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 237, 183), 1, true));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clear_btn.setBackground(new java.awt.Color(136, 137, 185));
        clear_btn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(230, 237, 183));
        clear_btn.setText("Clear");
        clear_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        clear_btn.setFocusable(false);
        clear_btn.setOpaque(false);
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        jPanel2.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 100, 40));

        show_btn.setBackground(new java.awt.Color(136, 137, 185));
        show_btn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        show_btn.setForeground(new java.awt.Color(230, 237, 183));
        show_btn.setText("Show Data");
        show_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        show_btn.setFocusable(false);
        show_btn.setOpaque(false);
        show_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_btnActionPerformed(evt);
            }
        });
        jPanel2.add(show_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 100, 40));

        search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_white_25px.png"))); // NOI18N
        search_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_btnMouseClicked(evt);
            }
        });
        jPanel2.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        search_name_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        search_name_txt.setForeground(new java.awt.Color(230, 237, 183));
        search_name_txt.setText("Book-Name");
        search_name_txt.setOpaque(false);
        search_name_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_name_txtMouseClicked(evt);
            }
        });
        jPanel2.add(search_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, 40));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 237, 183));
        jLabel2.setText("Search");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book Name", "Author", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, 280));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 460, 440));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 237, 183), 1, true));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_txt.setEditable(false);
        name_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        name_txt.setForeground(new java.awt.Color(230, 237, 183));
        name_txt.setText("Book Name");
        name_txt.setOpaque(false);
        name_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name_txtMouseClicked(evt);
            }
        });
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        jPanel3.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 237, 183));
        jLabel4.setText("Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(230, 237, 183));
        jLabel5.setText("Total Cost");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        price_txt.setEditable(false);
        price_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        price_txt.setForeground(new java.awt.Color(230, 237, 183));
        price_txt.setText("Price (Kyats)");
        price_txt.setOpaque(false);
        price_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                price_txtMouseClicked(evt);
            }
        });
        price_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_txtActionPerformed(evt);
            }
        });
        jPanel3.add(price_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 40));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 237, 183));
        jLabel7.setText("Price");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        qty_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        qty_txt.setForeground(new java.awt.Color(230, 237, 183));
        qty_txt.setText("Quantity");
        qty_txt.setOpaque(false);
        qty_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qty_txtMouseClicked(evt);
            }
        });
        qty_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty_txtActionPerformed(evt);
            }
        });
        jPanel3.add(qty_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 160, 40));

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane3.setViewportView(ta);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 420, 250));

        total_txt.setEditable(false);
        total_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        total_txt.setForeground(new java.awt.Color(230, 237, 183));
        total_txt.setOpaque(false);
        total_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total_txtMouseClicked(evt);
            }
        });
        total_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_txtActionPerformed(evt);
            }
        });
        jPanel3.add(total_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 110, 40));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 237, 183));
        jLabel6.setText("Quantity");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        buy_btn.setBackground(new java.awt.Color(136, 137, 185));
        buy_btn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        buy_btn.setForeground(new java.awt.Color(230, 237, 183));
        buy_btn.setText("Buy");
        buy_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buy_btn.setFocusable(false);
        buy_btn.setOpaque(false);
        buy_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_btnActionPerformed(evt);
            }
        });
        jPanel3.add(buy_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 100, 40));

        addcart.setBackground(new java.awt.Color(136, 137, 185));
        addcart.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        addcart.setForeground(new java.awt.Color(230, 237, 183));
        addcart.setText("Add to cart");
        addcart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addcart.setFocusable(false);
        addcart.setOpaque(false);
        addcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcartActionPerformed(evt);
            }
        });
        jPanel3.add(addcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 130, 40));

        search_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_white_25px.png"))); // NOI18N
        search_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_btn1MouseClicked(evt);
            }
        });
        jPanel3.add(search_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        search_name_txt1.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        search_name_txt1.setForeground(new java.awt.Color(230, 237, 183));
        search_name_txt1.setText("Book-Name");
        search_name_txt1.setOpaque(false);
        search_name_txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_name_txt1MouseClicked(evt);
            }
        });
        search_name_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_name_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(search_name_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 237, 183));
        jLabel3.setText("Search");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        payment_txt.setEditable(false);
        payment_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        payment_txt.setForeground(new java.awt.Color(230, 237, 183));
        payment_txt.setText("Payment");
        payment_txt.setOpaque(false);
        payment_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payment_txtMouseClicked(evt);
            }
        });
        payment_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_txtActionPerformed(evt);
            }
        });
        jPanel3.add(payment_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 160, 40));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 237, 183));
        jLabel8.setText("Payment");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, -1));

        change_txt.setEditable(false);
        change_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        change_txt.setForeground(new java.awt.Color(230, 237, 183));
        change_txt.setOpaque(false);
        change_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                change_txtMouseClicked(evt);
            }
        });
        change_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_txtActionPerformed(evt);
            }
        });
        jPanel3.add(change_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 110, 40));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(230, 237, 183));
        jLabel9.setText("Change");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 80, -1));

        print_btn.setBackground(new java.awt.Color(136, 137, 185));
        print_btn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        print_btn.setForeground(new java.awt.Color(230, 237, 183));
        print_btn.setText("Print");
        print_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        print_btn.setFocusable(false);
        print_btn.setOpaque(false);
        print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btnActionPerformed(evt);
            }
        });
        jPanel3.add(print_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 100, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 750, 440));

        clear_btn5.setBackground(new java.awt.Color(136, 137, 185));
        clear_btn5.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        clear_btn5.setForeground(new java.awt.Color(230, 237, 183));
        clear_btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back_to_40px.png"))); // NOI18N
        clear_btn5.setBorder(null);
        clear_btn5.setFocusable(false);
        clear_btn5.setOpaque(false);
        clear_btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(clear_btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void show_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_btnActionPerformed


        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        } catch (java.lang.ClassNotFoundException e) {  System.out.println(e);       }
        
        
        try {

            Connection c = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BookStore\\src\\database\\BookStore.mdb");
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

            ResultSet r = s.executeQuery("SELECT * FROM BookTable");


  
            String s1="";

            r.last();
            r.beforeFirst();
            
            while(r.next()) {

                String id = r.getString(5);
                String name = r.getString(1);
                String author = r.getString(2);
                String price = r.getString(3);
                String qty = r.getString(4);



                String[]data = { id,name,author,price,qty };
                
                DefaultTableModel m1 = (DefaultTableModel)tb.getModel();
                m1.addRow(data);
                tb.setModel(m1);

                
            }

            
            r.close();
            s.close();
            c.close();
            
                }catch(SQLException se) { System.out.println(se); }

        
    }//GEN-LAST:event_show_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed

        String[]col = {"ID","Book Name","Author","Price","Quantity" };
        tb.setModel(new DefaultTableModel(null,col));
        
    }//GEN-LAST:event_clear_btnActionPerformed

    private void search_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btnMouseClicked

        String bookname = search_name_txt.getText();
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        } catch (java.lang.ClassNotFoundException e) {  System.out.println(e);       }
        
        
        try {

            Connection c = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BookStore\\src\\database\\BookStore.mdb");
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

            ResultSet r = s.executeQuery("SELECT * FROM BookTable");

            r.last();
            r.beforeFirst();
            
            while(r.next()) {
                
                String db_name = r.getString(1);
                
                if (db_name.equals(bookname)) {
                    
                    String id = r.getString(5);
                    String name = r.getString(1);
                    String aut = r.getString(2);
                    String qq = r.getString(3);
                    String pr = r.getString(4);
                    
                    String[]data = {id,name,aut,qq,pr};

                DefaultTableModel m1 = (DefaultTableModel)tb.getModel();
                m1.addRow(data);
                tb.setModel(m1);
                    
                    
                } // found
                
            }
            r.close();
            s.close();
            c.close();
        }catch(SQLException se){ System.out.print(se); }
        
    }//GEN-LAST:event_search_btnMouseClicked

    private void search_name_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_name_txtMouseClicked
search_name_txt.setText("");
    }//GEN-LAST:event_search_name_txtMouseClicked

    private void name_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_txtMouseClicked
        name_txt.setText("");
    }//GEN-LAST:event_name_txtMouseClicked

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void qty_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qty_txtMouseClicked
        qty_txt.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_qty_txtMouseClicked

    private void qty_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty_txtActionPerformed

    private void price_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_price_txtMouseClicked
        price_txt.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_price_txtMouseClicked

    private void price_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_txtActionPerformed

    private void total_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_total_txtMouseClicked

    private void buy_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_btnActionPerformed

        int tot = Integer.parseInt(total_txt.getText());
        
        String s = JOptionPane.showInputDialog(null,"Total Cost : "+tot,"Enter your payment",JOptionPane.INFORMATION_MESSAGE);
        int pay = Integer.parseInt(s);
        
        payment_txt.setText(""+pay);
        
        int change=0;
        
        if (pay>=total) { 
            change = pay-total;
            change_txt.setText(""+change);
        }
        
        else {
            change = total-pay;
            change_txt.setText(""+change);
        }
        
        search_name_txt1.setText("");
        name_txt.setText("");
        qty_txt.setText("");
        price_txt.setText("");
        change_txt.setText("");
        total_txt.setText("");
        payment_txt.setText("");
        ta.setText("");
    }//GEN-LAST:event_buy_btnActionPerformed

    private void addcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcartActionPerformed

        String name = name_txt.getText();
        String price = price_txt.getText();
        String quantity = qty_txt.getText();

        y++;
        int calprice = Integer.parseInt(price);
        int calqty = Integer.parseInt(quantity);
        
        total = calprice * calqty;
        
        if (y==1) {
            ta.setText(ta.getText()+title+"\n"+y+"\t"+name+"\t\t"+price+"\t"+quantity+"\n");            
        } // 1st time
        
        else { 
        
            ta.setText(ta.getText()+y+"\t"+name+"\t\t"+price+"\t"+quantity+"\n");
        
        }

        allcost+=total;
        total_txt.setText(""+allcost);
        
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        } catch (java.lang.ClassNotFoundException e) {  System.out.println(e);       }
        
        
        try {

            Connection c = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BookStore\\src\\database\\BookStore.mdb");
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

            ResultSet r = s.executeQuery("SELECT * FROM BookTable");
            int final_q;
            r.last();
            r.beforeFirst();
            
            while(r.next()) {
                
                String db_name = r.getString(1);
                
                if (db_name.equals(name)) {

                    db_bookquantity = r.getString(4);

                    int db_q = Integer.parseInt(db_bookquantity);
                    
            
                   final_q = db_q - calqty;
                   
                   r.updateString(4,""+final_q);
                   r.updateRow();
                }
                
            }
                
            

            r.close();
            s.close();
            c.close();
        }catch(SQLException se){ }
        
        
    }//GEN-LAST:event_addcartActionPerformed

    private void search_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btn1MouseClicked

                String bookname = search_name_txt1.getText();
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        } catch (java.lang.ClassNotFoundException e) {  System.out.println(e);       }
        
        
        try {

            Connection c = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BookStore\\src\\database\\BookStore.mdb");
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

            ResultSet r = s.executeQuery("SELECT * FROM BookTable");
            
            r.last();
            r.beforeFirst();
            
            while(r.next()) {
                
                String db_name = r.getString(1);
                
                if (db_name.equals(bookname)) {
                    String name = r.getString(1);
                    String price = r.getString(3);
                    db_bookquantity = r.getString(4);
                    name_txt.setText(name);
                    price_txt.setText(price);
                }
                
            }
                

            r.close();
            s.close();
            c.close();
        }catch(SQLException se){ }

        
    }//GEN-LAST:event_search_btn1MouseClicked

    private void search_name_txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_name_txt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_search_name_txt1MouseClicked

    private void search_name_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_name_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_name_txt1ActionPerformed

    private void total_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_txtActionPerformed

    private void payment_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payment_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_payment_txtMouseClicked

    private void payment_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payment_txtActionPerformed

    private void change_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_change_txtMouseClicked

    private void change_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_change_txtActionPerformed

    private void print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_print_btnActionPerformed

    private void clear_btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btn5ActionPerformed

        setVisible(false);
        Admin_Menu obj = new Admin_Menu();
        obj.setVisible(true);
    }//GEN-LAST:event_clear_btn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Sales obj = new Sales();
        obj.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcart;
    private javax.swing.JButton buy_btn;
    private javax.swing.JTextField change_txt;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton clear_btn5;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField payment_txt;
    private javax.swing.JTextField price_txt;
    private javax.swing.JButton print_btn;
    private javax.swing.JTextField qty_txt;
    private javax.swing.JLabel search_btn;
    private javax.swing.JLabel search_btn1;
    private javax.swing.JTextField search_name_txt;
    private javax.swing.JTextField search_name_txt1;
    private javax.swing.JButton show_btn;
    private javax.swing.JTextArea ta;
    private javax.swing.JTable tb;
    private javax.swing.JTextField total_txt;
    // End of variables declaration//GEN-END:variables
}
